# Generated by Django 4.2.5 on 2023-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenFuncContainsFunc',
            fields=[
                ('idContainsFunc', models.IntegerField(db_column='idContainsFunc', primary_key=True, serialize=False)),
                ('idGenLaborFunc', models.IntegerField(db_column='idGenLaborFunc')),
                ('idLaborFunc', models.IntegerField(db_column='idLaborFunc')),
            ],
            options={
                'db_table': 'tblgenfunccontainsfunc',
            },
        ),
        migrations.CreateModel(
            name='GenLaborFuncContainsProf',
            fields=[
                ('idContainsProf', models.IntegerField(db_column='idContainsProf', primary_key=True, serialize=False)),
                ('idGenLaborFunc', models.IntegerField(db_column='idGenLaborFunc')),
                ('idProfession', models.IntegerField(db_column='idProfession')),
            ],
            options={
                'db_table': 'tblgenfunccontainsprof',
            },
        ),
        migrations.CreateModel(
            name='LaborFuncContainsKnowledge',
            fields=[
                ('idContainsKnowledge', models.IntegerField(db_column='idContainsKnowledge', primary_key=True, serialize=False)),
                ('idLaborFunc', models.IntegerField(db_column='idLaborFunc')),
                ('idNecKnowledge', models.IntegerField(db_column='idNecKnowledge')),
            ],
            options={
                'db_table': 'tbllaborfunccontainsknowledge',
            },
        ),
        migrations.CreateModel(
            name='LaborFuncContainsSkill',
            fields=[
                ('idContainsSkill', models.IntegerField(db_column='idContainsSkill', primary_key=True, serialize=False)),
                ('idLaborFunc', models.IntegerField(db_column='idLaborFunc')),
                ('idNecSkill', models.IntegerField(db_column='idNecSkill')),
            ],
            options={
                'db_table': 'tbllaborfunccontainsskill',
            },
        ),
        migrations.CreateModel(
            name='NecessaryKnowledge',
            fields=[
                ('idNecKnowledge', models.IntegerField(db_column='idNecKnowledge', primary_key=True, serialize=False)),
                ('necKnowledgeName', models.TextField(db_column='necKnowledgeName')),
                ('embeddingKnowledge', models.TextField(db_column='embeddingKnowledge')),
            ],
            options={
                'db_table': 'tblnecessaryknowledge',
            },
        ),
        migrations.CreateModel(
            name='NecessarySkill',
            fields=[
                ('idNecSkill', models.IntegerField(db_column='idNecSkill', primary_key=True, serialize=False)),
                ('necSkillName', models.TextField(db_column='necSkillName')),
                ('embeddingSkill', models.TextField(db_column='embeddingSkill')),
            ],
            options={
                'db_table': 'tblnecessaryskill',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('idProfession', models.IntegerField(db_column='idProfession', primary_key=True, serialize=False)),
                ('professionName', models.TextField(db_column='professionName')),
            ],
            options={
                'db_table': 'tblprofession',
            },
        ),
    ]
