name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: prof_standart
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE prof_standart;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "SECRET_KEY = 'django-insecure-dummy-secret'" > ./djangoProject/secrets.py
          echo "USER = 'root'" >> ./djangoProject/secrets.py
          echo "PASSWORD = 'root'" >> ./djangoProject/secrets.py
          coverage run --source=. -m manage.py test
      - name: Upload coverage data to coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pip install coveralls
            coveralls --service=github
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}